### ISSUE TITLE
Issue with getting stats

### ISSUE THREAD

**Issue by GrapeArts** [xcodinas/fortnite-python#18]
So I am currently trying to get the stats of the player, and it is telling me that my player object has no attribute "get stats"

full traceback 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Player' object has no attribute 'getStats'
>>>

from fortnite_python import Fortnite
from fortnite_python.domain import Mode
from fortnite_python.domain import Platform
fortnite=Fortnite('')<----- Not sharing token
player = fortnite.player('AwayThrone', Platform.PC)
stats = player.getStats(Mode.DUO)

**Comment by xcodinas** [comment]
The getStats method was changed to get_stats in [1] so you should do:

`stats = player.get_stats(Mode.DUO)`

The readme file  had the old method in the examples.
