### ISSUE TITLE
Using this in a discord bot

### ISSUE THREAD

**Issue by FightMan01** [xcodinas/fortnite-python#26]
I'm using this in a discord bot, and when I'm write an invalid player name, it'll crashes the bot.

**Comment by xcodinas** [comment]
With this infomation I can't really know what's really going on but it may be related to `UnknownPlayerError` [0] being raised. If that's the case you should use a try except.

[0] https://github.com/xcodinas/fortnite-python/blob/2be81e6a99d5f705124646a67f64f8229d043bfd/fortnite_python/exceptions.py#L13

**Comment by FightMan01** [comment]
@xcodinas 
Actually the error was in this code. It raises the UnknownPlayerError after it crashes.
But I modified this section in the base.py file and now it works fine.
```py
    def player(self, player=None, platform=Platform.PC):
        try:
            endpoint = 'profile/%s/%s' % (platform.value, player)
            data = self.client.request(endpoint)
            if 'accountId' in data:
                return Player(data)
            error = False
        except:
            error = True
        if error:
            raise UnknownPlayerError
```

**Comment by xcodinas** [comment]
It seems that it's an api error as sometimes it returns an html instead of a json so when we try to decode the json it crashes as it's not a json.

I've contacted with them and I will update the code if needed when they reply.

**Comment by RedstonedLife** [comment]
@xcodinas Surround the statement that decodes the data to json with a JSONError try except. and if it catches the exception it should return None, so later down the road if it happens again people can check if it returned None or a dict object.
