### ISSUE TITLE
Add Nintendo Switch to platforms 

### ISSUE THREAD

**Issue by merc1er** [xcodinas/fortnite-python#37]
I noticed that Nintendo switch is available in the Platform class: https://github.com/xcodinas/fortnite-python/blob/master/fortnite_python/domain.py#L4

Any plans to support it?

**Comment by michaellunzer** [comment]
Hey @merc1er, I only play on the Switch (and 1-2 games on the iPad) and started getting my stats when I changed the Platform to `Platform.GAMEPAD`

I noticed that the URL changed when I selected the "gamepad" option on the site:

<img width="442" alt="Screen Shot 2020-08-27 at 11 51 16 PM" src="https://user-images.githubusercontent.com/10967175/91531081-0e08a080-e8c1-11ea-92c2-253c73228218.png">



```
from fortnite_python import Fortnite
from fortnite_python.domain import Platform
from fortnite_python.domain import Mode

fortnite = Fortnite('api key here')

player = fortnite.player('username here', Platform.GAMEPAD)
stats = player.get_stats(Mode.SQUAD)

print(player)
print(stats.top1)
```

**Comment by merc1er** [comment]
Working, thanks!
