### ISSUE TITLE
'Stats' object has no attribute 'kills_match'

### ISSUE THREAD

**Issue by Sh3tix** [xcodinas/fortnite-python#38]
Hello, when I try this : `winrate_solo = player.get_stats(Mode.SOLO).kills_match`

I have this error : **'Stats' object has no attribute 'kills_match'**

Any help ?

**Comment by xcodinas** [comment]
There's no such attribute on the stats object, you can check all the attributes with:
`dir(player.get_stats(Mode.SOLO)`
